-- CREATE TABLE "737710058431053836" (
-- 	"server_name"	TEXT NOT NULL,
-- 	"server_id"	INTEGER NOT NULL,
-- 	"member_count"	INTEGER NOT NULL,
-- 	"total_channels"	INTEGER NOT NULL,
-- 	"created_at"	INTEGER NOT NULL,
-- 	"owner_id"	INTEGER NOT NULL,
-- 	"joined_at_date"	INTEGER NOT NULL,
-- 	PRIMARY KEY("server_id")
-- );